export const LOADING = 'LOADING_DEPARTMENT';
export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';
export const GET_ALL_DEPARTMENT_BY_ID = 'GET_ALL_DEPARTMENT_BY_ID';
export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
export const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
